#!/usr/bin/bash
# 
# Script name: dmconf
# Description: Choose from a list of configuration files to edit
# Dependencies: dmenu
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor


# Defining the text editor to use
DMEDITOR="vim"

# An array of options to choose
# You can edit this list to add/remove config files
# "NAME - PATH "
declare -a options=(
"bash_profile- $HOME/.profile"
"bashrc - $HOME/.bashrc"
"ctags - $HOME/.ctags"
"lynx - /etc/lynx/lynx.cfg"
"nvim - $HOME/.config/nvim/init.vim"
"R - $HOME/.Rprofile"
"tmux - $HOME/.tmux.conf"
"vim - $HOME/.vimrc"
"zathura - $HOME/.config/zathura/zathurarc"
"quit"
)

# Piping the above array into dmenu.
# We use "printf '%s\n'" to fomat the array one item to a line.
choice=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Edit config:' )

# What to do when/if choose 'quit'
if [[ "$choice" == "quit" ]]; then
        echo "Program terminated." && exit 1

elif [ "$choice" ]; then
        cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
        $DMEDITOR "$cfg"

else
        echo "Program terminated." && exit 1
fi
