#!/usr/bin/bash
# 
# Script name: dmsearch
# Description: Search various search engines (inspired by surfraw)
# Dependencies: dmenu and a web browser
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# Contributors: Derek Taylor


# Defining the text editor to use
DMBROWSER="chromium"


# Search Engines


# An array of options to choose
# You can edit this list to add/remove config files
# "NAME - PATH "
declare -a options=(
"amazon - https://www.amazon.com/s?k="
"archaur - https://aur.archlinux.org/packages/?O=0&K="
"archpkg - https://archlinux.org/packages/?sort=&q="
"archwiki - https://wiki.archlinux.org/index.php?search="
"arxiv - https://arxiv.org/search/?searchtype=all&source=header&query="
"bbcnews - https://www.bbc.co.uk/search?q="
"bing - https://www.bing.com/search?q="
"brave - https://search.brave.com/search?q="
"cnn - https://www.cnn.com/search?q="
"craigslist - https://www.craigslist.org/search/sss?query="
"debianpkg - https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords="
"duckduckgo - https://duckduckgo.com/?q="
"ebay - https://www.ebay.com/sch/i.html?&_nkw="
"github - https://github.com/search?q="
"gitlab - https://gitlab.com/search?search="
"google - https://www.google.com/search?q="
"googleOpenSource - https://opensource.google/projects/search?q="
"googlenews - https://news.google.com/search?q="
"googleflights - https://www.google.com/travel/flights?q="
"gumtree - https://www.gumtree.com/search?search_category=all&q="
"odysee - https://odysee.com/$/search?q="
"qwant - https://www.qwant.com/?q="
"reddit - https://www.reddit.com/search/?q="
"refseek - https://www.refseek.com/search?q="
"sourceforge - https://sourceforge.net/directory/?q="
"stackoverflow - https://stackoverflow.com/search?q="
"swisscows - https://swisscows.com/web?query="
"wikipedia - https://en.wikipedia.org/w/index.php?search="
"wiktionary - https://en.wiktionary.org/w/index.php?search="
"yandex - https://yandex.com/search/?text="
"youtube - https://www.youtube.com/results?search_query="
)

# Picking a search engine
while [ -z "$engine" ]; do
        enginelist=$(printf '%s\n' "${options[@]}" | dmenu -i -l 20 -p 'Choose search engine:') || exit
        engineurl=$(echo "$enginelist" | awk '{print $NF}')
        engine=$(echo "$enginelist" | awk '{print $1}')
done
echo "$engine"

# Searching the chosen engine
while [ -z "$query" ]; do
        query=$(echo '' | dmenu -i -l 20 -p "Searching $engine:") || exit
done

# Display search results in web browser
$DMBROWSER "$engineurl""$query" &
