#!/bin/bash

# gets the bib citation from a pdf file or a doi using crossref.org API.

# -z means length of string is 0.
[ -z "$1"  ] && echo "Give either a pdf file or a DOI as an argument" && exit

if [ -f "$1" ]; then
        # Try to get DOI from pdfinfo or pdftotext output
        doi=$(pdfinfo "$1" | grep -io "doi:.*") ||
        doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*\/.*") || # 2>/dev/null sends 'erases' standard error.
        doi=$(pdftotext "$1" 2>/dev/null - | grep -io "doi.*\/.*") ||
        exit 1

else
        doi="$1"
fi

doi=$(echo $doi | awk '{print $1}')
# check crossref.org for the bib citation
curl -s "https://api.crossref.org/works/$doi/transform/application/x-bibtex" -w "\\n"


